### ISSUE TITLE
Sync to WebDav Server fails

### ISSUE THREAD

**Issue by bschnitz** [Ninjaclasher/abeluna#1]
Upload of items to a WebDav Server fails. (Download is possible.) Following traceback is possibly connected to the issue:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/abeluna/sync/server.py", line 261, in _synchronize_todolist
    caldav.Todo(cal.client, data=vcal, parent=cal.calendar, id=local_item.uid).save()
  File "/home/ben/.local/lib/python3.9/site-packages/caldav/objects.py", line 1501, in save
    self._create(self.data, self.id, path)
  File "/home/ben/.local/lib/python3.9/site-packages/caldav/objects.py", line 1538, in _get_data
    return self._icalendar_instance.to_ical()
  File "/usr/lib/python3.9/site-packages/icalendar/cal.py", line 426, in to_ical
    content_lines = self.content_lines(sorted=sorted)
  File "/usr/lib/python3.9/site-packages/icalendar/cal.py", line 414, in content_lines
    for name, value in self.property_items(sorted=sorted):
  File "/usr/lib/python3.9/site-packages/icalendar/cal.py", line 315, in property_items
    properties += subcomponent.property_items(sorted=sorted)
AttributeError: 'NoneType' object has no attribute 'property_items'
```

Testet with the WebDav server of mail.de .

**Comment by bschnitz** [comment]
I think I got the problem. If the timezone in Settings -> General is set to 'UTC', 'generate_vtimezone' in abeluna/util.py will return None and that cannot be handled by the icalender lib.

**Comment by Ninjaclasher** [comment]
Thanks for the bug report! I've pushed a fix to master. Let me know if you experience any other issues.

**Comment by bschnitz** [comment]
Great, thank You! And thanks for this nice piece of software.
